spring.application.name=Simple-Pharmacy
spring.config.import=optional:file:.env[.properties]
#----------------------------db config  
spring.datasource.url=${DB_PROD_URL:${DB_LOCAL_URL}}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


#----------------------hibernet configuration jap  
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect